version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: db_estudioad
      MYSQL_USER: estudioad
      MYSQL_PASSWORD: dev

    volumes:
      - mysqldata:/var/lib/mysql
      - ./Config/init-db:/docker-entrypoint-initdb.d
    
    networks:
      - dev-network
      
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - dev-network

  backend:

    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings  # Ajusta esto según la ubicación de tu configuración
    depends_on:
      - mysql
      - redis

    ports:
      - "8000:8000"
    
    volumes:
      - ./Backend/sources:/home/web/sources

    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  mysqldata: