version: "3.8"

services:
  frontend:
    
    build:
      context: ./Frontend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    
    volumes:
      - ./Frontend:/home/web

    networks:
      - estudio-network

  backend:

    build:
      context: ./Backend
      dockerfile: Dockerfile

    ports:
      - "8088:8088"
    
    volumes:
      - ./Backend/sources:/home/web/sources

    networks:
      - estudio-network

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - estudio-network

  mysql:
    image: mysql:latest
    container_name: mysql-server
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: ...
      MYSQL_DATABASE: db_estudioad
      MYSQL_USER: estudioad
      MYSQL_PASSWORD: ...

    volumes:
      - mysqldata:/var/lib/mysql
      - ./Config/init-db:/docker-entrypoint-initdb.d
    
    networks:
      - estudio-network

networks:
  estudio-network:
    driver: bridge

volumes:
  mysqldata: